[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_SUPABASE_URL = "https://mhwbsiygowgcmwapqvzq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1od2JzaXlnb3dnY213YXBxdnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzA1OTIsImV4cCI6MjA2NjMwNjU5Mn0.7XByxFrM2h3ARPSa51HM13FFH6e8eJNU_PKs8ROzV80"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://mhwbsiygowgcmwapqvzq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1od2JzaXlnb3dnY213YXBxdnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzA1OTIsImV4cCI6MjA2NjMwNjU5Mn0.7XByxFrM2h3ARPSa51HM13FFH6e8eJNU_PKs8ROzV80"